# Generated by Django 4.0.3 on 2022-03-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_alter_contato_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='biografia'),
        ),
    ]
