# Generated by Django 4.0.3 on 2022-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_contato_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
